#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern "C" void _Ca_reg(void);
extern "C" void _CaDynamics_E2_reg(void);
extern "C" void _Ca_LVAst_reg(void);
extern "C" void _DASyn_reg(void);
extern "C" void _Ih_reg(void);
extern "C" void _Im_reg(void);
extern "C" void _Im_ms_reg(void);
extern "C" void _K_Pst_reg(void);
extern "C" void _K_Tst_reg(void);
extern "C" void _Kv3_GPe_reg(void);
extern "C" void _NO_reg(void);
extern "C" void _NaTa_t_reg(void);
extern "C" void _NaTs2_t_reg(void);
extern "C" void _Nap_Et2_reg(void);
extern "C" void _SK_E2_reg(void);
extern "C" void _SKv3_1_reg(void);
extern "C" void _bk_ch_reg(void);
extern "C" void _bk_fs_reg(void);
extern "C" void _bk_ms_reg(void);
extern "C" void _ca_ch_reg(void);
extern "C" void _cadyn_fs_reg(void);
extern "C" void _cadyn_ms_reg(void);
extern "C" void _cal12_ms_reg(void);
extern "C" void _cal13_ms_reg(void);
extern "C" void _cal_ch_reg(void);
extern "C" void _caldyn_ms_reg(void);
extern "C" void _can_fs_reg(void);
extern "C" void _can_ms_reg(void);
extern "C" void _cap_ch_reg(void);
extern "C" void _caq_fs_reg(void);
extern "C" void _caq_ms_reg(void);
extern "C" void _car_fs_reg(void);
extern "C" void _car_ms_reg(void);
extern "C" void _cat32_ms_reg(void);
extern "C" void _cat33_ms_reg(void);
extern "C" void _hcn12_ch_reg(void);
extern "C" void _hd_lts_reg(void);
extern "C" void _im_lts_reg(void);
extern "C" void _insert_ik_ina_ica_reg(void);
extern "C" void _it_lts_reg(void);
extern "C" void _kaf_fs_reg(void);
extern "C" void _kaf_lts_reg(void);
extern "C" void _kaf_ms_reg(void);
extern "C" void _kas_fs_reg(void);
extern "C" void _kas_ms_reg(void);
extern "C" void _kcnq_ch_reg(void);
extern "C" void _kdb_lts_reg(void);
extern "C" void _kdr_fs_reg(void);
extern "C" void _kdr_lts_reg(void);
extern "C" void _kdr_ms_reg(void);
extern "C" void _kdrb_lts_reg(void);
extern "C" void _kir_reg(void);
extern "C" void _kir23_ch_reg(void);
extern "C" void _kir23_lts_reg(void);
extern "C" void _kir2_ch_reg(void);
extern "C" void _kir_fs_reg(void);
extern "C" void _kir_ms_reg(void);
extern "C" void _kv2_ch_reg(void);
extern "C" void _kv4_ch_reg(void);
extern "C" void _nACh_reg(void);
extern "C" void _na2_ch_reg(void);
extern "C" void _na3_lts_reg(void);
extern "C" void _na_ch_reg(void);
extern "C" void _naf_fs_reg(void);
extern "C" void _naf_lts_reg(void);
extern "C" void _naf_ms_reg(void);
extern "C" void _naf_th_reg(void);
extern "C" void _par_ggap_reg(void);
extern "C" void _pka_buffer_reg(void);
extern "C" void _sk_ch_reg(void);
extern "C" void _sk_fs_reg(void);
extern "C" void _sk_ms_reg(void);
extern "C" void _tmgabaa_reg(void);
extern "C" void _tmglut_reg(void);
extern "C" void _tmglut_M1RH_D1_reg(void);
extern "C" void _tmglut_double_reg(void);
extern "C" void _vecevent_reg(void);

extern "C" void modl_reg() {
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");
    fprintf(stderr, " \"mech/Ca.mod\"");
    fprintf(stderr, " \"mech/CaDynamics_E2.mod\"");
    fprintf(stderr, " \"mech/Ca_LVAst.mod\"");
    fprintf(stderr, " \"mech/DASyn.mod\"");
    fprintf(stderr, " \"mech/Ih.mod\"");
    fprintf(stderr, " \"mech/Im.mod\"");
    fprintf(stderr, " \"mech/Im_ms.mod\"");
    fprintf(stderr, " \"mech/K_Pst.mod\"");
    fprintf(stderr, " \"mech/K_Tst.mod\"");
    fprintf(stderr, " \"mech/Kv3_GPe.mod\"");
    fprintf(stderr, " \"mech/NO.mod\"");
    fprintf(stderr, " \"mech/NaTa_t.mod\"");
    fprintf(stderr, " \"mech/NaTs2_t.mod\"");
    fprintf(stderr, " \"mech/Nap_Et2.mod\"");
    fprintf(stderr, " \"mech/SK_E2.mod\"");
    fprintf(stderr, " \"mech/SKv3_1.mod\"");
    fprintf(stderr, " \"mech/bk_ch.mod\"");
    fprintf(stderr, " \"mech/bk_fs.mod\"");
    fprintf(stderr, " \"mech/bk_ms.mod\"");
    fprintf(stderr, " \"mech/ca_ch.mod\"");
    fprintf(stderr, " \"mech/cadyn_fs.mod\"");
    fprintf(stderr, " \"mech/cadyn_ms.mod\"");
    fprintf(stderr, " \"mech/cal12_ms.mod\"");
    fprintf(stderr, " \"mech/cal13_ms.mod\"");
    fprintf(stderr, " \"mech/cal_ch.mod\"");
    fprintf(stderr, " \"mech/caldyn_ms.mod\"");
    fprintf(stderr, " \"mech/can_fs.mod\"");
    fprintf(stderr, " \"mech/can_ms.mod\"");
    fprintf(stderr, " \"mech/cap_ch.mod\"");
    fprintf(stderr, " \"mech/caq_fs.mod\"");
    fprintf(stderr, " \"mech/caq_ms.mod\"");
    fprintf(stderr, " \"mech/car_fs.mod\"");
    fprintf(stderr, " \"mech/car_ms.mod\"");
    fprintf(stderr, " \"mech/cat32_ms.mod\"");
    fprintf(stderr, " \"mech/cat33_ms.mod\"");
    fprintf(stderr, " \"mech/hcn12_ch.mod\"");
    fprintf(stderr, " \"mech/hd_lts.mod\"");
    fprintf(stderr, " \"mech/im_lts.mod\"");
    fprintf(stderr, " \"mech/insert_ik_ina_ica.mod\"");
    fprintf(stderr, " \"mech/it_lts.mod\"");
    fprintf(stderr, " \"mech/kaf_fs.mod\"");
    fprintf(stderr, " \"mech/kaf_lts.mod\"");
    fprintf(stderr, " \"mech/kaf_ms.mod\"");
    fprintf(stderr, " \"mech/kas_fs.mod\"");
    fprintf(stderr, " \"mech/kas_ms.mod\"");
    fprintf(stderr, " \"mech/kcnq_ch.mod\"");
    fprintf(stderr, " \"mech/kdb_lts.mod\"");
    fprintf(stderr, " \"mech/kdr_fs.mod\"");
    fprintf(stderr, " \"mech/kdr_lts.mod\"");
    fprintf(stderr, " \"mech/kdr_ms.mod\"");
    fprintf(stderr, " \"mech/kdrb_lts.mod\"");
    fprintf(stderr, " \"mech/kir.mod\"");
    fprintf(stderr, " \"mech/kir23_ch.mod\"");
    fprintf(stderr, " \"mech/kir23_lts.mod\"");
    fprintf(stderr, " \"mech/kir2_ch.mod\"");
    fprintf(stderr, " \"mech/kir_fs.mod\"");
    fprintf(stderr, " \"mech/kir_ms.mod\"");
    fprintf(stderr, " \"mech/kv2_ch.mod\"");
    fprintf(stderr, " \"mech/kv4_ch.mod\"");
    fprintf(stderr, " \"mech/nACh.mod\"");
    fprintf(stderr, " \"mech/na2_ch.mod\"");
    fprintf(stderr, " \"mech/na3_lts.mod\"");
    fprintf(stderr, " \"mech/na_ch.mod\"");
    fprintf(stderr, " \"mech/naf_fs.mod\"");
    fprintf(stderr, " \"mech/naf_lts.mod\"");
    fprintf(stderr, " \"mech/naf_ms.mod\"");
    fprintf(stderr, " \"mech/naf_th.mod\"");
    fprintf(stderr, " \"mech/par_ggap.mod\"");
    fprintf(stderr, " \"mech/pka_buffer.mod\"");
    fprintf(stderr, " \"mech/sk_ch.mod\"");
    fprintf(stderr, " \"mech/sk_fs.mod\"");
    fprintf(stderr, " \"mech/sk_ms.mod\"");
    fprintf(stderr, " \"mech/tmgabaa.mod\"");
    fprintf(stderr, " \"mech/tmglut.mod\"");
    fprintf(stderr, " \"mech/tmglut_M1RH_D1.mod\"");
    fprintf(stderr, " \"mech/tmglut_double.mod\"");
    fprintf(stderr, " \"mech/vecevent.mod\"");
    fprintf(stderr, "\n");
  }
  _Ca_reg();
  _CaDynamics_E2_reg();
  _Ca_LVAst_reg();
  _DASyn_reg();
  _Ih_reg();
  _Im_reg();
  _Im_ms_reg();
  _K_Pst_reg();
  _K_Tst_reg();
  _Kv3_GPe_reg();
  _NO_reg();
  _NaTa_t_reg();
  _NaTs2_t_reg();
  _Nap_Et2_reg();
  _SK_E2_reg();
  _SKv3_1_reg();
  _bk_ch_reg();
  _bk_fs_reg();
  _bk_ms_reg();
  _ca_ch_reg();
  _cadyn_fs_reg();
  _cadyn_ms_reg();
  _cal12_ms_reg();
  _cal13_ms_reg();
  _cal_ch_reg();
  _caldyn_ms_reg();
  _can_fs_reg();
  _can_ms_reg();
  _cap_ch_reg();
  _caq_fs_reg();
  _caq_ms_reg();
  _car_fs_reg();
  _car_ms_reg();
  _cat32_ms_reg();
  _cat33_ms_reg();
  _hcn12_ch_reg();
  _hd_lts_reg();
  _im_lts_reg();
  _insert_ik_ina_ica_reg();
  _it_lts_reg();
  _kaf_fs_reg();
  _kaf_lts_reg();
  _kaf_ms_reg();
  _kas_fs_reg();
  _kas_ms_reg();
  _kcnq_ch_reg();
  _kdb_lts_reg();
  _kdr_fs_reg();
  _kdr_lts_reg();
  _kdr_ms_reg();
  _kdrb_lts_reg();
  _kir_reg();
  _kir23_ch_reg();
  _kir23_lts_reg();
  _kir2_ch_reg();
  _kir_fs_reg();
  _kir_ms_reg();
  _kv2_ch_reg();
  _kv4_ch_reg();
  _nACh_reg();
  _na2_ch_reg();
  _na3_lts_reg();
  _na_ch_reg();
  _naf_fs_reg();
  _naf_lts_reg();
  _naf_ms_reg();
  _naf_th_reg();
  _par_ggap_reg();
  _pka_buffer_reg();
  _sk_ch_reg();
  _sk_fs_reg();
  _sk_ms_reg();
  _tmgabaa_reg();
  _tmglut_reg();
  _tmglut_M1RH_D1_reg();
  _tmglut_double_reg();
  _vecevent_reg();
}
